### ISSUE TITLE
Proposal: add an "excluded" option to disable check

### ISSUE THREAD

**Issue by fertapric** [rrrene/credo-proposals#10]
### Environment

* Credo version (`mix credo -v`): 0.8.3
* Erlang/Elixir version (`elixir -v`): 1.4.4
* Operating system: Darwin 16.6.0 x86_64

### Proposal

Exclude a specific set of files for a specific check. Here is an example:

```elixir
%{
      # ...other configuration
      checks: [
        {Credo.Check.Consistency.ExceptionNames. exclude: ["lib/foo/bar.ex:13"]},
        {Credo.Check.Consistency.LineEndings, excluded: ["lib/foo/bar.ex", ~r"/test/"]},
```

For further reference, [Rubocop provides this functionality](http://rubocop.readthedocs.io/en/latest/configuration/#includingexcluding-files):

```
Rails/HasAndBelongsToMany:
  Exclude:
    - app/models/problematic.rb
```

**Comment by chulkilee** [comment]
Another use case:

When there is a parser module (e.g. using nimble_parsec), for readability users may want to skip some credo checks, since some code may seem more like "DSL".

**Comment by n0um3n4** [comment]
Any news on this matter?

**Comment by rrrene** [comment]
This has been included (*pun intended*) for some time. I missed closing this proposal.

You can read up on the current implementation here: https://hexdocs.pm/credo/check_params.html#files

Not sure if I should keep this issue open, as there might still be some constructive controversy to this solution 👍

**Comment by fertapric** [comment]
@rrrene from my perspective (as original requester), this issue can be closed. Thanks for looking into it 🙌
