### ISSUE TITLE
Proposal: Documentation of Possible Check Parameters

### ISSUE THREAD

**Issue by philippneugebauer** [rrrene/credo-proposals#12]
I really like the effort and the progress which was done till now.

I just wanted to ask if there is any list of check parameters beside in the code available and if it's worth to collect such information. If yes, I will dig into the code and provide a PR to give sth back :)

**Comment by rrrene** [comment]
Hi, this has been part of `miy credo explain` and the HTML docs for a while now. 

Thanks for the proposal. I just forgot to close it ✌️
