### ISSUE TITLE
Proposal: Add ignore_heredocs to Credo.Check.Readability.MaxLineLength in addition to ignore_strings

### ISSUE THREAD

**Issue by smetana** [rrrene/credo-proposals#16]
Is it possible to split ignore_strings or to add additional ignore_heredocs option to Credo.Check.Readability.MaxLineLength?
We turn off ignore_strings because of bug https://github.com/rrrene/credo/issues/389
But it will be extremely useful to make it work for heredocs only.

**Comment by rrrene** [comment]
This has been implemented for some time and I forgot to close this. 

Thanks for suggesting it! ✌️
