### ISSUE TITLE
Proposal: check use, import, alias, require have same order

### ISSUE THREAD

**Issue by progsmile** [rrrene/credo-proposals#22]
Hi there! Thanks for package!
I didn't find rule to check order for directives: use, import, alias, require 
Wish it would be, to make code more consistent
It would be option to set particular order: `{Credo.Check.Consistency.ModuleDirectivesOrder, order: [:use, :import, :require, :alias]}`

So, if you don't mind I'll try to implement this and do pull request

Here are examples:
- Valid
`use Ecto.Schema`
`import Ecto.Query`
`alias Ecto.Paging`
`require Logger`

- Also valid 
`import Ecto.Query`
`require Logger`

- Invalid
`require Logger`
`import Ecto.Query`
`alias Ecto.Paging`

What do you think?

**Comment by progsmile** [comment]
Is it actual? I saw 2 prs and they seems to be stale.. 
https://github.com/rrrene/credo/pull/689
https://github.com/rrrene/credo/pull/588

Like @whatyouhide approach: 
> For now, I suggest starting with just `use`/`import`/`alias`/`require`. The reason for that ordering is that they are from most "dangerous" (`use` can do many hidden things) to least dangerous.

@doomspork @sascha-wolf you both have prs, so does this part (`use`/`import`/`alias`/`require`) implemented? I may also try to finish it with own pr :)

**Comment by sasa1977** [comment]
Related to this, a few months ago I wrote a custom check for my client which verifies the ordering of various module parts. We currently enforce the following order:

```
 1. @shortdoc
 2. @moduledoc
 3. @behaviour
 4. use
 5. import
 6. alias
 7. require
 8. custom module attributes
 9. defstruct
10. @opaque
11. @type
12. @typep
13. @callback
14. @macrocallback
15. @optional_callbacks
16. public guards
17. public macros
18. public functions
19. behaviour callbacks
20. private functions
```

which is an adaptation of [this styleguide](https://github.com/christopheradams/elixir_style_guide#module-attribute-ordering).

The ordering is currently hardcoded, but with a bit of work it could be made configurable.

Would there be some interest to accept this in credo?

**Comment by rrrene** [comment]
@sasa1977 Very much +1.

It would be even more useful, if the configuration could be "fuzzy" and would encourage teams to find their personal "best practices" along the way:

Suppose the configuration for your example would be 

```elixir
[
  :@shortdoc,
  :@moduledoc,
  :@behaviour,
  :use,
  :import,
  :alias,
  :require,
  :custom_module_attributes,
  :defstruct,
  :@opaque,
  :@type,
  :@typep,
  :@callback,
  :@macrocallback,
  :@optional_callbacks,
  :public_guards,
  :public_macros,
  :public_functions,
  :behaviour_callbacks,
  :private_functions
]
```

then I think it would be great if the user does not necessarily have to define all of the possible "member types", but could instead use 

```elixir
[
  :@behaviour,
  :defstruct,
  :use,
]
```

to simply say: "I want to ensure that we always put `@behaviour` before `defstruct` calls and those before `use` calls, but I do not want to impose more rules about the order inside our modules at this point".

I think the ability to be less pedantic would help a great deal in adopting a common order in modules gradually throughout projects, if people are able to say "The strict requirement is that X and Y come first".

WDYT?

**Comment by sasa1977** [comment]
Yeah, I agree! One question is should credo ship with some default proposal, or should we leave everything to the clients?

**Comment by rrrene** [comment]
I am very open to the idea of some "sensible defaults" here. 

After re-reading [the section of the christopheradams styleguide](https://github.com/christopheradams/elixir_style_guide#module-attribute-ordering) I just can't shake the feeling that this is too specific to be a sensible default.

But we could come up with something less dogmatic as default while still providing the ability to be super pedantic (and including an example configuration for Christopher's guide in the docs/as an alternative config).

Could you think of some order that is widely applicable? 

I am asking because, for example, even the differentiation in "first all `def` and then all `defp`" is something that a team can agree upon, but many popular Elixir libs show that this is not a must. Having `@shortdoc/@moduledoc` at the top and `defstruct` after that, but before any function definitions on the other hand might be something most people can agree upon (also just as an example).

**Comment by sasa1977** [comment]
> Having `@shortdoc/@moduledoc` at the top and `defstruct` after that, but before any function definitions

One thing which comes to mind. Partial order config (only some elements are listed), should always starts from the top of the module. In other words, the config `~w/@shortdoc @moduledoc defstruct/a` would mean that all other elements (other module attributes, functions, macros, ...) must appear after `defstruct`. 

With such config semantics, I think that a sensible default might be:

```elixir
~w/
@shortdoc,
@moduledoc,
@behaviour,
use,
import,
alias,
require,
/a
```

Such default would also resolve this particular issue. WDYT?

**Comment by rrrene** [comment]
Sounds good to me :+1:

Am So., 16. Feb. 2020 um 12:06 Uhr schrieb Saša Jurić <
notifications@github.com>:

**Comment by sasa1977** [comment]
PR is available [here](https://github.com/rrrene/credo/pull/747).

**Comment by rrrene** [comment]
Thx everyone! The check by @sasa1977 will be part of Credo `v1.3` :+1:
