### ISSUE TITLE
Proposal: show rule name in output

### ISSUE THREAD

**Issue by chengyin** [rrrene/credo-proposals#34]
### Environment

System:
  Credo: 1.0.4
  Elixir: 1.8.1
  Erlang: 21

### What were you trying to do?

When trying to disable a lint rule for a particular issue, it's hard to find out what is the name of the rule since the default output does not include that info.

### Expected outcome

Including lint rule name corresponding to each warning/error.

### Actual outcome

No lint rule name. Had to use `mix credo explain` to find it per issue.

**Comment by neslinesli93** [comment]
That would be awesome! I imagine having the rule name at the end of the explaining text, in square brackets.  For example:

```
┃ Refactoring opportunities
┃
┃ [R] ↗ An `if` block with a negated condition should not contain an else block. [Credo.Check.Refactor.NegatedConditionsWithElse]
┃       lib/phoenix/channel.ex:26 (Phoenix.Channel.subscribe)
┃ [R] → Function is too complex (max ABC is 15, was 43). [Credo.Check.Refactor.ABCSize]
┃       lib/phoenix/router.ex:563:8 (Phoenix.Router.add_resources)
┃ [R] → Function is too complex (max ABC is 15, was 16). [Credo.Check.Refactor.ABCSize]
┃       lib/phoenix/router/socket.ex:12:12 (Phoenix.Router.Socket.channel)
┃
```

**Comment by chess4ever** [comment]
Maybe the refactoring opportunities could also be grouped by rule.

**Comment by georgfaust** [comment]
this would be greatly appreciated. If too long, one could consider giving a interger-ID to each check.

**Comment by rrrene** [comment]
You can display the check name by using `--verbose` in current versions of Credo. Sorry for not clarifying (and closing) this earlier. ✌️
