### ISSUE TITLE
Proposal: Accept paths in the CLI

### ISSUE THREAD

**Issue by robotpistol** [rrrene/credo-proposals#35]
### Environment

* Credo version (`mix credo -v`): 1.0.2
* Erlang/Elixir version (`elixir -v`): 1.8.0
* Operating system: linux

### What were you trying to do?

I want the CLI to accept a directory path and to check all elixir files in that path.  
Also least accept multiple file paths.

It seems that 

### Expected outcome
Passing in a directory `mix credo apps/myapp`
```
Checking 123 source files!
```

Passing in 2 file paths `mix credo apps/myapp/lib/application.ex apps/myapp/lib/myapp.ex`
```
Checking 2 source files
```
### Actual outcome
File path
```
No files found!

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.05 seconds (0.03s to load, 0.02s running checks)
0 mods/funs, found no issues.
```

Multiple file paths
```
Checking 1 source file ...

Please report incorrect results: https://github.com/rrrene/credo/issues

Analysis took 0.05 seconds (0.03s to load, 0.02s running checks)
0 mods/funs, found no issues.
```

**Comment by rrrene** [comment]
This has been added in the meantime and I forgot to mention it here ✌️
