### ISSUE TITLE
Proposal: Allow passing a list of files to `mix credo`

### ISSUE THREAD

**Issue by BachirC** [rrrene/credo-proposals#4]
While trying to add credo analysis in my `pre-commit` git hook on staged files, I noticed that actually only the first file of the list was anaylzed. (Credo : `0.6.1`, Elixir : `1.4.1`, default `.credo.exs`)

So being able to do something like : `mix credo [options] file1.exs file2.ex file3.ex` would be really nice imo ! :)

**Comment by ffloyd** [comment]
+1

**Comment by joskar** [comment]
Is someone working on this to make this happen?

**Comment by rrrene** [comment]
Credo `1.2.0-rc3` now features `--files-included`/`--files-excluded` switches.

Both switches accept files, globs and can be given multiple times, potentially combining both.

```
mix credo --files-included file1.exs
mix credo --files-included file*.exs
mix credo --files-included file1.exs --files-included file2.ex --files-included file3.ex
```

We'll see if we can implement this in the proposed way, but for now this is what we have :+1:

**Comment by NorthIsUp** [comment]
is `mix credo --files-included file1.exs file2.ex file3.ex` also an option? When trying to pass through other build tools getting the `--files-included` to interlace with the files can be difficult or impossible to script.

**Comment by rrrene** [comment]
> is `mix credo --files-included file1.exs file2.ex file3.ex` also an option?

Unfortunately, no. I also would not consider that a viable candidate and do not know of any tool accepting a cumulative option like that. How you would you even parse that? (honest question?)

**Comment by camilohollanda** [comment]
Being able to pass a list of files would be really useful for pre-commit hooks.

**Comment by rrrene** [comment]
@prem-prakash That is possible, please see [this comment](https://github.com/rrrene/credo-proposals/issues/4#issuecomment-575793508).

```
mix credo --files-included file1.exs --files-included file2.ex --files-included file3.ex
```

**Comment by camilohollanda** [comment]
See this comment https://github.com/rrrene/credo-proposals/issues/4#issuecomment-590501208

**Comment by rrrene** [comment]
> See this comment https://github.com/rrrene/credo-proposals/issues/4#issuecomment-590501208

I am sorry, but I already replied to that comment, urging the author to state how that should work. 

I would pose the same question to you: How would the OptionParser be able to parse this unambiguously?

You could also point out tools that work this way, so we could look up how they do it. 👍

**Comment by camilohollanda** [comment]
Hi Rene, sorry for insisting. In fact, OptionParser is a bit limited in that it cannot deal with a list of values for an option in another way than repeating the option prefix. Thanks for your attention.

**Comment by rrrene** [comment]
I did not want to discourage you. ✌️ 

My understanding is that it is more or less trivial to control the files in a scripting environment like BASH:

```bash
function run_credo {
    cmd=(mix credo)
    for file in "$@"; do
        cmd+=("--files-included" "$file")
    done

    command "${cmd[@]}"
}

run_credo `ls lib/*.ex`
```

I am just curious how we could provide a more convenient version that is as precise as the culmulative option solution while making it more approachable for non-scripting experts.

**Comment by alex9spiridonov** [comment]
> > See this comment [#4 (comment)](https://github.com/rrrene/credo-proposals/issues/4#issuecomment-590501208)
> 
> I am sorry, but I already replied to that comment, urging the author to state how that should work.
> 
> I would pose the same question to you: How would the OptionParser be able to parse this unambiguously?
> 
> You could also point out tools that work this way, so we could look up how they do it. 👍

@rrrene
you can see rubocop for ruby
https://docs.rubocop.org/rubocop/usage/basic_usage.html
you can pass rubocop a list of files and directories to check

**Comment by rrrene** [comment]
@alex9spiridonov Rubocop does not work in the discussed fashion. Please re-read the discussion above 👍

**Comment by camilohollanda** [comment]
@rrrene yes it does

![Screen Shot 2022-08-29 at 16 40 38](https://user-images.githubusercontent.com/775409/187284337-ec713976-82fc-4c73-92a1-4951c1c38dd5.png)

**Comment by rrrene** [comment]
@prem-prakash there is no need to be passive agressive here. 

The option discussed above was to have a single option that receives the space-separated list of files (see the linked and quoted comment as well as the discussion re: OptionParser). 

You are posting a screenshot of a program that receives a list of files as arguments. I'm sorry, but that is not the same thing.

**Comment by camilohollanda** [comment]
@rrrene sorry, it was not my intention to sound passive-aggressive.
This is just a very wanted feature to simplify credo use especially for big projects.

**Comment by alex9spiridonov** [comment]
@prem-prakash maybe it will be useful for you.
In our company we wrote this CI script to check only modified files.
This script builds string like `--files-included changed_file1.exs --files-included changed_file2.ex --files-included changed_file3.ex` and pass it to mix credo.
```yml
- CHANGED_FILES=$(git diff-tree -r --no-commit-id --name-only --merge-base --diff-filter=d origin/master HEAD)
- FILES_INCLUDED=""
- for f in $(echo $CHANGED_FILES | tr ";" "\n") ; do FILES_INCLUDED="$FILES_INCLUDED --files-included $f" ; done
- if [ ! -z "$CHANGED_FILES" ] ; then echo $FILES_INCLUDED | xargs sudo -E mix credo --strict ; fi
```

**Comment by saveman71** [comment]
Note to future readers: [credo 1.7 now supports this out of the box](https://hexdocs.pm/credo/changelog.html#allow-passing-of-multiple-files-to-mix-task)
