### ISSUE TITLE
Question: `not is_nil` -> is this a smell?

### ISSUE THREAD

**Issue by pdgonzalez872** [rrrene/credo-proposals#49]
Hi! This is not a proposal, nor a check (yet at least), but instead is just a question. I think this is probably the best place to ask this since I love the value Credo adds to any project.

With that said, I'm working on a project and I'm seeing a lot of "not is_nil(arg)" guards in the project, like so:

```
def fun(%{external_id: external_id, id: id}) when not is_nil(external_id) do
   ...
end
```

I'm wondering if that's a smell. If so, maybe it warrants a Credo warning/refactor suggestion? I know we can pattern match, and I prefer the solution:

```
def fun(%{external_id: nil, id: id}) do
   ...
end

# guarantees it is not nil
def fun(%{external_id: external_id, id: id}) do
   ...
end
```

### What do you want Credo to do?

Unsure if I want Credo to do anything at the moment. Maybe it is just me favoring the explicit nil pattern match over the "not is_nil" guard.

### Which existing behaviour would change?

Current behavior is that we get no warnings. As I said, I'm not sure we should change anything, other than me getting used to that pattern.

Thanks for the work! I love Credo.

**Comment by rrrene** [comment]
This is an interesting proposal, especially since I, too, prefer the pattern matching way you describe. 

This would definitely add a lot of value as a check.

One thing I am unsure about is if this would have to be an opt-in one, since there are probably situations where I still would prefer the guard, e.g. when I want the process to crash in case there is a `nil` value given.

**Comment by pdgonzalez872** [comment]
Very cool! Would you mind if i tried to create the check? That'd be a cool
exercise for me and if you think it would still add value by then we could
move on to the next stage. If not, no worries!

**Comment by rrrene** [comment]
Absolutely. Go for it 👍🏻

> Am 23.01.2020 um 08:19 schrieb Paulo Daniel Gonzalez <notifications@github.com>:
> 
> ﻿Very cool! Would you mind if i tried to create the check? That'd be a cool
> exercise for me and if you think it would still add value by then we could
> move on to the next stage. If not, no worries!
>

**Comment by pdgonzalez872** [comment]
Closing this in favor of https://github.com/rrrene/credo/pull/738

Thanks @rrrene!
