### ISSUE TITLE
How to: DuplicatedCode check in umbrella project

### ISSUE THREAD

**Issue by EasterPeanut** [rrrene/credo-proposals#51]
### What were you trying to do? ###

Is it possible to check for duplicated code **only** in the scope of an app, so not project wide?

**Comment by rrrene** [comment]
This should be possible using differently named configs within the same config file, where you scope the configs to the respective subdirectories and only enable the `DuplicatedCode` check.

Or you could run `mix credo --only DuplicatedCode` in the individual apps.

**Comment by EasterPeanut** [comment]
> This should be possible using differently named configs within the same config file, where you scope the configs to the respective subdirectories and only enable the `DuplicatedCode` check.

Of course 🤦‍♀️Thanks!
