### ISSUE TITLE
New Check: ensure test files end with .exs

### ISSUE THREAD

**Issue by egze** [rrrene/credo-proposals#62]
### What do you want Credo to do?
Credo should ensure that all files with `_test.` in them, end with a `.exs`. This will prevent bugs where a developer would name the file like so `my_test.ex` and will get skipped by `mix test`.

### Which existing behaviour would change?
None?

Would love to submit a PR.

**Comment by rrrene** [comment]
> Would love to submit a PR.

Please do :+1:

**Comment by egze** [comment]
@rrrene done https://github.com/rrrene/credo/pull/821
