### ISSUE TITLE
New check: use refute instead of assert false

### ISSUE THREAD

**Issue by Darhazer** [rrrene/credo-proposals#69]
### What do you want Credo to do?

Given code like:
```
assert Map.has_key?(map, :key) == false
```

propose changing it to
```
refute Map.has_key?(map, :key)
```

**Comment by rrrene** [comment]
Closing this because it would produce false positives. 

Your very example shows this, as asserting on `false` is the right way to test a predicate function. 

You would not want that test to pass if the function returned `nil`.
