### ISSUE TITLE
New Check: require moduledoc to be on top of the module

### ISSUE THREAD

**Issue by Darhazer** [rrrene/credo-proposals#70]
### What do you want Credo to do?

Given a module that has a moduledoc, require the moduledoc to be in the beginning, and not after aliases, imports, etc.
Example bad code:

```
defmodule AppWeb.PageLive do
  use AppWeb, :live_view
  alias App.SomeModule

  @moduledoc """
  This holds the App main view.
  """
```

**Comment by pdgonzalez872** [comment]
I thought there was something for this already? https://github.com/rrrene/credo/commit/679c3dc6baf10e33050841f96dec2935bf4a1dd2

**Comment by pdgonzalez872** [comment]
Was renamed: https://github.com/rrrene/credo/blob/61c81fa95d636671e1b382d7293f8ae2d57b52ad/lib/credo/check/readability/strict_module_layout.ex

**Comment by Darhazer** [comment]
Thank you :bow:  I don't know how I've missed that. Well - I do, it's just disabled by default.
I'll make sure to enable all checks next time, before submitting a feature request.

**Comment by pdgonzalez872** [comment]
> I'll make sure to enable all checks next time, before submitting a feature request.

It's all good! Great to meet you! Hope that check helps you :heart: :rocket:
