### ISSUE TITLE
New Check: Warning dbg

### ISSUE THREAD

**Issue by wingyplus** [rrrene/credo-proposals#80]
### Precheck

* Try to phrase your title in a way that hints at your proposals area of effect
    * For proposing a new check, name your issue "New Check: ..."
    * For proposing a new feature, name your issue "Feature: ..."
    * You get the gist :-)
* **For bugs, please report them** in [Credo's main repo](https://github.com/rrrene/credo).

### What do you want Credo to do?

Instead of `IO.inspect` warning usage. We should warning `dbg` that introduce in incoming Elixir 1.14 also. For example:

```elixir
a_function() |> dbg() # warning.
dbg(a_function())      # warning.
Kernel.dbg(...)            # warning.
Elixir.Kernel.dbg(...)   # warning.
```

### Which existing behaviour would change?

I expected that we should have a new rules for this like IO.inspect. :)

**Comment by wingyplus** [comment]
Another case that I'm not sure how credo behave:

First, `dbg` is variable:


```elixir
defmodule A do
  def b() do
    dbg = "hello"
    dbg  # valid or invalid?
  end
end
```


The second case is dbg is function in the module:

```elixir
defmodule A do
  def dbg(), do: true

  def b() do
    dbg  # valid or invalid?
    dbg() # valid or invalid? 
  end
end
```

**Comment by rrrene** [comment]
I think this would be a great check.

You can differentiate the cases in your reply by looking at the AST 👍

**Comment by rrrene** [comment]
This is part of Credo. :tada:
