### ISSUE TITLE
New config: allow specific modules on Credo.Check.Readability.ModuleNames

### ISSUE THREAD

**Issue by BobrImperator** [rrrene/credo-proposals#83]
### What do you want Credo to do?
Today the Credo.Check.Readability.ModuleNames errors for any use of an underscore (_) in a module name.

In our case, while working with multiple versions of APIs, we decided to add versions in the module names .e.g `V1_1.SampleModule`

It'd be nice to have an option to make it configurable, we'd still like to apply the rule, but not for any specific segments.
i.e

#### Default

Credo.Sample_Module will pass ❌
Credo.Another_Module.Sample_Module will fail ❌

#### Configured
allow: [Sample_Module]

Credo.Sample_Module will pass ✅
Credo.Another_Module.Sample_Module will fail ❌

### Which existing behaviour would change?

No breaking changes for existing behaviour.
Instead it allows to configure the rule to not raise an issue for specific segments.

**Comment by rrrene** [comment]
I close this "proposal" since it is not really a proposal at this point since the author had already opened a PR for this feature when he "proposed" it here.

**Comment by oliverbarnes** [comment]
@rrrene what's with the attitude? You're acting like @BobrImperator is acting in bad faith or something. And in the PR comments you dismiss everything like it's a preposterous idea.

If submitting a proposal in an issue after a PR was opened is not part of your project's workflow, fair enough. Just point it out. Not a big deal.

I followed his process internally, he took the time to work on this and submitted it with the best of intentions, nothing out of line about it. He was looking forward to contributing to Credo.

I don't know what ticked you off, but I hope you're just having a bad day. We have plenty of respect for the work you put in here.

**Comment by rrrene** [comment]
@oliverbarnes  I was just pointing out that, unless this is a [temporal pincer movement](https://www.quora.com/What-is-a-temporal-pincer-movement-in-the-movie-TENET), we can skip the discussion here since there is already a PR open.

While I do not want to start a typical "somebody is wrong on the internet" discussion, I am unsure what you mean by "in the PR comments you dismiss everything".
