### ISSUE TITLE
Feature: ignore decorate annotation for Credo.Check.Readability.StrictModuleLayout

### ISSUE THREAD

**Issue by btkostner** [rrrene/credo-proposals#86]
### What do you want Credo to do?

Right now the `Credo.Check.Readability.StrictModuleLayout` will trigger a `module_attribute` error with this code.

```elixir
  @decorate cacheable(cache: Cache)
  def test!() do
	true
  end
```

This code is from the [decorator](https://github.com/arjan/decorator) library and [Nebulex](https://github.com/cabol/nebulex), but the decorator library itself is used by a lot of other projects. It would be nice if it didn't error out this check. The solution should be to just ignore `@decorate` completely to match how `@spec` works (because it is attached to the function head and can't be sorted.)

### Which existing behaviour would change?

The `Credo.Check.Readability.StrictModuleLayout` module would no longer error with `@decorate` above function heads.

**Comment by rrrene** [comment]
Sounds good to me. If we find a way to make this a parameter for the check, I would definitely merge a PR for it.

**Comment by rrrene** [comment]
This became [part of Credo](https://github.com/rrrene/credo/pull/1048) 🎉
